# Generated by Django 2.2.4 on 2019-11-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('judge_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nhsee_judge',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('project_title', models.CharField(max_length=100, null=True)),
                ('project_category', models.CharField(max_length=100, null=True)),
                ('avg_score', models.FloatField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('z_score', models.FloatField(null=True)),
                ('scaled_score', models.FloatField(null=True)),
                ('scaled_rank', models.IntegerField(null=True)),
                ('scaled_z', models.FloatField(null=True)),
                ('iself_score', models.FloatField(null=True)),
                ('iself_rank', models.IntegerField(null=True)),
                ('no_show_project', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'nhsee_project',
            },
        ),
        migrations.CreateModel(
            name='studet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhsee.project')),
            ],
        ),
        migrations.CreateModel(
            name='judge_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_score', models.FloatField(null=True)),
                ('plan_score', models.FloatField(null=True)),
                ('action_score', models.FloatField(null=True)),
                ('result_analysis_score', models.FloatField(null=True)),
                ('communication_score', models.FloatField(null=True)),
                ('raw_score', models.FloatField(null=True)),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nhsee.judge')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nhsee.project')),
            ],
        ),
    ]
