# Generated by Django 2.2.4 on 2019-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhsee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='judge_assignment',
            new_name='judgeassignment',
        ),
        migrations.DeleteModel(
            name='challenge',
        ),
        migrations.AlterModelTable(
            name='judgeassignment',
            table='nhsee_judgeassignment',
        ),
        migrations.DeleteModel(
            name='studet',
        ),
    ]
